# Site Settings
name: CoEvolve project
title: CoEvolve project | The website of the ERC funded project CoEvolve
description: Understanding the co-evolution of Life and Planet through the lens of trace element availability
tags:
  - science
  - co-evolution
  - microbiology
  - ERC Starting Grant
  - Giovannelli Lab
  - microbiology
show_hero: true
menu:
  - title: Home
    url: /
  - title: Project
    url: /project
  - title: Team
    url: /team
  - title: Expeditions
    url: /expeditions
  - title: Educators
    url: /educators
  - title: Media
    url: /media
  - title: Scientists
    url: /scientists
  - title: Contact
    url: /contact
email: donato.giovannelli@unina.it


# Social Media Settings
# Remove the item if you don't need it
github_username: giovannellilab
twitter_username: d_giovannelli
instagram_username: donatogiovannelli


# Posts Settings
show_time_bar: false
show_modal_on_exit: false
show_modal_on_finish_post: false
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.coevolve.eu/" # the base hostname & protocol for your site
google_analytics: "G-WLWEDBWSZZ"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v1.0
