name: CoEvolve project
title: CoEvolve project | The website of the ERC funded project CoEvolve
description: The website of the ERC funded project CoEvolve
tags:
  - science
  - co-evolution
  - ERC Starting Grant
  - Giovannelli Lab
  - microbiology
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
email: donato.giovannelli@unina.it
